-- migration: 20260818000004_learning_media_grip-strength-longevity.sql
-- Media for learning material: grip-strength-longevity (explainer, body / strength).
-- Fase A of the content-media pipeline, run automatically by the Learning publisher.
--
-- Assets were generated by tools/content-media/generate.mjs from the art-director spec at
-- learning-drops/inbox/grip-strength-longevity/media-spec.json:
--   · cover.webp            768x1152 (2:3), textless, Gemini 2.5 Flash Image  -> source 'gemini-api'
--   · infographic.pt.webp   1080x1920, code-rendered from brand tokens (SVG/resvg) -> source 'manual'
--   · infographic.en.webp   1080x1920, code-rendered from brand tokens (SVG/resvg) -> source 'manual'
--
-- Art direction note: both the cover and the infographic had to defend the article's central
-- claim — grip strength is a MARKER, not a lever. The cover is deliberately NOT a hand, a
-- gripper or a flexing arm (any of which would visually assert the exact misread the text
-- spends three passages dismantling); it is a single lit leaf at the tip of an otherwise bare
-- branch, the tree dissolving into the dark behind it — the last living leaf reports on the
-- whole tree, and you cannot heal the tree by painting the leaf. The infographic's hero stat is
-- the ACTIONABLE dose (10-20 percent lower mortality risk at 30-60 min/week of strength
-- training, Momma et al., BJSM 2022), not the 16-percent-per-5kg figure, which stays inside
-- point 1 as a risk reading so it can never be read as a training target.
--
-- The cover took 2 attempts: the Gemini image endpoint returned a transient 503 UNAVAILABLE
-- ("high demand") on the first call. Not a key/billing failure; the retry succeeded.
--
-- All three were uploaded to the public `learning-media` bucket BEFORE this migration and
-- verified reachable (HTTP 200, image/webp, byte sizes matching the local files) so the feed
-- can never 404:
--   supabase storage ls ss:///learning-media/grip-strength-longevity/ --experimental --linked
-- `path` is BUCKET-RELATIVE on purpose; the client builds the URL via learningMediaUrl().
-- Cover is stored as an absolute hero_image_url, matching the rest of the catalog.
-- migrations are write-once; never edit after applying.

update public.learning_material
set hero_image_url = 'https://uneqnpyzevosznwkmvvo.supabase.co/storage/v1/object/public/learning-media/grip-strength-longevity/cover.webp',
    updated_at = now()
where slug = 'grip-strength-longevity';

insert into public.learning_material_media (material_id, kind, locale, path, source, meta)
select m.id, 'infographic', v.locale, v.path, 'manual',
       jsonb_build_object('width', 1080, 'height', 1920)
from public.learning_material m
cross join (values
  ('pt', 'grip-strength-longevity/infographic.pt.webp'),
  ('en', 'grip-strength-longevity/infographic.en.webp')
) as v(locale, path)
where m.slug = 'grip-strength-longevity'
on conflict (material_id, kind, locale) do nothing;
