-- migration: 20260727000001_desired_sub_score.sql
-- purpose: add a third per-sub score source, 'desired' (aspirational targets),
--          so the Desejada pillar can store "where I want to get to" per sub.
--
-- affected tables: character_sub_score, assessment_log — widen the source
--                  CHECK constraint on both to allow 'desired'.
-- new rpcs:        none (set_sub_score replaced in place; bulk delegates).
-- breaking?        no — purely additive. Existing 'self'/'questionnaire' rows
--                  and every current reader are untouched; 'desired' rows are
--                  created lazily on first write, exactly like 'questionnaire'.
--
-- notes:
--   migrations are write-once; never edit after applying.
--   The legacy 3-arg set_sub_score(text,text,smallint) overload from
--   20260503000004 is dropped here: it validated only self/questionnaire (so
--   it would raise on 'desired'), and coexisting with the 4-arg version it
--   created a PostgREST overload-resolution ambiguity. The single remaining
--   4-arg function serves every caller — a 3-named-arg call (useSetSubScore)
--   resolves to it with p_score_decimal defaulted, the same integer path.

begin;

-- ─── 1. Widen the source CHECK on both tables ────────────────────────────
-- Constraint names are auto-generated by Postgres; find and drop whichever
-- CHECK references `source`, then re-add with the third value. Robust even
-- if the constraint were named non-conventionally.
do $$
declare
  c text;
begin
  select conname into c
  from pg_constraint
  where conrelid = 'public.character_sub_score'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) ilike '%source%';
  if c is not null then
    execute format(
      'alter table public.character_sub_score drop constraint %I', c);
  end if;
end $$;

alter table public.character_sub_score
  add constraint character_sub_score_source_check
  check (source in ('self', 'questionnaire', 'desired'));

do $$
declare
  c text;
begin
  select conname into c
  from pg_constraint
  where conrelid = 'public.assessment_log'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) ilike '%source%';
  if c is not null then
    execute format(
      'alter table public.assessment_log drop constraint %I', c);
  end if;
end $$;

alter table public.assessment_log
  add constraint assessment_log_source_check
  check (source in ('self', 'questionnaire', 'desired'));

-- ─── 2. Drop the legacy 3-arg overload ───────────────────────────────────
drop function if exists public.set_sub_score(text, text, smallint);

-- ─── 3. Replace set_sub_score (4-arg) with 'desired' allowed ─────────────
-- Body identical to 20260507000008 except the validation list now includes
-- 'desired'. Re-grant EXECUTE (a plain CREATE OR REPLACE keeps grants, but
-- we dropped an overload above, so be explicit).
create or replace function public.set_sub_score(
  p_source        text,
  p_sub_id        text,
  p_score         smallint,
  p_score_decimal numeric default null
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_int smallint;
  v_dec numeric;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;
  if p_source not in ('self', 'questionnaire', 'desired') then
    raise exception 'Invalid source: %', p_source;
  end if;

  -- Decimal path takes precedence: derive integer from it via floor() so
  -- existing readers (hex pip count, sparkline) keep working untouched.
  if p_score_decimal is not null then
    if p_score_decimal < 0 or p_score_decimal > 5 then
      raise exception 'score_decimal must be between 0 and 5, got %', p_score_decimal;
    end if;
    v_dec := round(p_score_decimal::numeric, 2);
    v_int := greatest(0, least(5, floor(v_dec)::int))::smallint;
  else
    if p_score < 0 or p_score > 5 then
      raise exception 'Score must be between 0 and 5, got %', p_score;
    end if;
    v_int := p_score;
    v_dec := null;
  end if;

  if not exists (select 1 from public.dimension_sub where id = p_sub_id) then
    raise exception 'Unknown sub_id: %', p_sub_id;
  end if;

  insert into public.character_sub_score
    (character_id, source, sub_id, score, score_decimal)
  values
    (auth.uid(), p_source, p_sub_id, v_int, v_dec)
  on conflict (character_id, source, sub_id)
  do update set
    score         = excluded.score,
    score_decimal = excluded.score_decimal,
    updated_at    = now();

  insert into public.assessment_log
    (character_id, source, sub_id, score)
  values
    (auth.uid(), p_source, p_sub_id, v_int);
end $$;

grant execute on function
  public.set_sub_score(text, text, smallint, numeric) to authenticated;

commit;
