-- migration: 20260811000006_learning_media_ten-second-balance-test.sql
-- Media for learning material: ten-second-balance-test (explainer, body / dexterity).
-- Fase A of the content-media pipeline, run automatically by the Learning publisher.
--
-- Assets were generated by tools/content-media/generate.mjs from the art-director spec at
-- learning-drops/inbox/ten-second-balance-test/media-spec.json:
--   · cover.webp            768x1152 (2:3), textless, Gemini 2.5 Flash Image  -> source 'gemini-api'
--   · infographic.pt.webp   1080x1920, code-rendered from brand tokens (SVG/resvg) -> source 'manual'
--   · infographic.en.webp   1080x1920, code-rendered from brand tokens (SVG/resvg) -> source 'manual'
--
-- All three were uploaded to the public `learning-media` bucket BEFORE this migration and
-- verified reachable (HTTP 200, image/webp) so the feed can never 404:
--   supabase storage ls ss:///learning-media/ten-second-balance-test/ --experimental --linked
-- `path` is BUCKET-RELATIVE on purpose; the client builds the URL via learningMediaUrl().
-- Cover is stored as an absolute hero_image_url, matching the rest of the catalog.
-- migrations are write-once; never edit after applying.

update public.learning_material
set hero_image_url = 'https://uneqnpyzevosznwkmvvo.supabase.co/storage/v1/object/public/learning-media/ten-second-balance-test/cover.webp',
    updated_at = now()
where slug = 'ten-second-balance-test';

insert into public.learning_material_media (material_id, kind, locale, path, source, meta)
select m.id, 'infographic', v.locale, v.path, 'manual',
       jsonb_build_object('width', 1080, 'height', 1920)
from public.learning_material m
cross join (values
  ('pt', 'ten-second-balance-test/infographic.pt.webp'),
  ('en', 'ten-second-balance-test/infographic.en.webp')
) as v(locale, path)
where m.slug = 'ten-second-balance-test'
on conflict (material_id, kind, locale) do nothing;
