-- migration: 20260729000310_learning_media_catch-up-sleep-weekend.sql
-- Media for the catch-up-sleep-weekend explainer (Fase A: cover + infographic).
-- Assets were generated by tools/content-media/generate.mjs from
--   learning-drops/inbox/catch-up-sleep-weekend/media-spec.json (art-director agent)
--   and uploaded to the public `learning-media` bucket BEFORE this migration ran:
--     learning-media/catch-up-sleep-weekend/cover.webp          (gemini-api, 768x1152)
--     learning-media/catch-up-sleep-weekend/infographic.pt.webp (manual/code-rendered, 1080x1920)
--     learning-media/catch-up-sleep-weekend/infographic.en.webp (manual/code-rendered, 1080x1920)
--   All three verified HTTP 200 + content-type image/webp, so the feed cannot 404.
-- `path` is BUCKET-RELATIVE — the client builds the URL via learningMediaUrl().
-- migrations are write-once; never edit after applying.

-- cover -> hero_image_url on the material itself
update public.learning_material
set hero_image_url = 'https://uneqnpyzevosznwkmvvo.supabase.co/storage/v1/object/public/learning-media/catch-up-sleep-weekend/cover.webp'
where slug = 'catch-up-sleep-weekend';

-- infographics -> learning_material_media (one row per locale)
insert into public.learning_material_media
  (material_id, kind, locale, path, source, meta)
select m.id, 'infographic', a.locale, a.path, 'manual',
       jsonb_build_object('width', 1080, 'height', 1920)
from public.learning_material m
cross join (values
  ('pt', 'catch-up-sleep-weekend/infographic.pt.webp'),
  ('en', 'catch-up-sleep-weekend/infographic.en.webp')
) as a(locale, path)
where m.slug = 'catch-up-sleep-weekend'
on conflict (material_id, kind, locale) do update set
  path   = excluded.path,
  source = excluded.source,
  meta   = excluded.meta;
