-- migration: 20260824000002_learning_media_play-deprivation-adults.sql
-- Media for learning material: play-deprivation-adults (explainer, craft / play).
-- Fase A of the content-media pipeline, run automatically by the Learning publisher.
--
-- Assets were generated by tools/content-media/generate.mjs from the art-director spec at
-- learning-drops/inbox/play-deprivation-adults/media-spec.json:
--   · cover.webp            768x1152 (2:3), textless, Gemini 2.5 Flash Image  -> source 'gemini-api'
--   · infographic.pt.webp   1080x1920, code-rendered from brand tokens (SVG/resvg) -> source 'manual'
--   · infographic.en.webp   1080x1920, code-rendered from brand tokens (SVG/resvg) -> source 'manual'
--
-- Art direction: the cover is a dark shelf holding seven identical glass jars — six worn smooth
-- from handling, the seventh at the end untouched under dust, lit from the side. It renders
-- Panksepp's literal shelf (PLAY stored beside FEAR and PANIC/GRIEF) and the article's closing
-- line ('um sistema que a sua agenda classificou como opcional') in one sober, textless still
-- life. The brief explicitly BANNED the obvious register — no toys, no crayons, no children, no
-- ball pits, no cartoon rats — because the piece is neuroscience-serious about an underrated
-- instinct, and a whimsical cover would have argued against its own text. Top two thirds are
-- left dark and empty for the title overlay.
--
-- INFOGRAPHIC TEXT WAS REWRITTEN BEFORE THIS MIGRATION, and the reason matters: the first
-- render fit the art-director copy to the renderer by ellipsizing it, and the truncation landed
-- exactly on the evidence caveats. Point 2 was cut at 'Em humanos há…', dropping 'só correlação:
-- ninguém testou reintroduzir brincadeira', and the stat caption was cut at '(Proyer, 2017) — o…',
-- dropping 'o instrumento mede o traço, não a privação'. That inverted the meaning of the card:
-- it would have implied 1.796 adults validated something about play DEPRIVATION, which is the
-- precise overclaim the article spends three passages dismantling. The copy was shortened to the
-- renderer's real budget (45 chars x 3 lines per point body, 40 x 2 for the stat caption) so that
-- both caveats survive in full. All 20 text fields were re-simulated through the wrap function
-- and confirmed to render with zero ellipsis before upload.
--
-- All three were uploaded to the public `learning-media` bucket BEFORE this migration and
-- verified reachable (HTTP 200, image/webp, byte sizes matching the local files exactly:
-- cover 13590, infographic.pt 102078, infographic.en 89462) so the feed can never 404:
--   supabase storage ls ss:///learning-media/play-deprivation-adults/ --experimental --linked
-- `path` is BUCKET-RELATIVE on purpose; the client builds the URL via learningMediaUrl().
-- Cover is stored as an absolute hero_image_url, matching the rest of the catalog.
-- migrations are write-once; never edit after applying.

update public.learning_material
set hero_image_url = 'https://uneqnpyzevosznwkmvvo.supabase.co/storage/v1/object/public/learning-media/play-deprivation-adults/cover.webp',
    updated_at = now()
where slug = 'play-deprivation-adults';

insert into public.learning_material_media (material_id, kind, locale, path, source, meta)
select m.id, 'infographic', v.locale, v.path, 'manual',
       jsonb_build_object('width', 1080, 'height', 1920)
from public.learning_material m
cross join (values
  ('pt', 'play-deprivation-adults/infographic.pt.webp'),
  ('en', 'play-deprivation-adults/infographic.en.webp')
) as v(locale, path)
where m.slug = 'play-deprivation-adults'
on conflict (material_id, kind, locale) do nothing;
