-- migration: 20260728000001_learning_cover_deep_work.sql
-- purpose: set the cover (hero_image_url) for the existing material
--          'summary-deep-work'. Cover was generated by the content-media
--          pipeline (Gemini 2.5 Flash Image, 2:3, textless) and uploaded to
--          learning-media/summary-deep-work/cover.webp — the first cover
--          produced 100% via API rather than a manual NotebookLM/GEM export.
--
-- affected tables: learning_material (one row: hero_image_url)
-- new rpcs:        none
-- breaking?        no — idempotent single-row UPDATE, safe to re-run
--
-- notes:
--   migrations are write-once; never edit after applying.
--   the cover file was uploaded via `supabase storage cp` before this ran, so
--   the feed never 404s.

begin;

update public.learning_material
set hero_image_url =
      'https://uneqnpyzevosznwkmvvo.supabase.co/storage/v1/object/public/learning-media/summary-deep-work/cover.webp',
    updated_at = now()
where slug = 'summary-deep-work';

commit;
