-- migration: 20260811000002_learning_media_weak-ties-job-search.sql
-- Media for the weak-ties-job-search explainer (Fase A: cover + infographic).
-- Autonomous Learning publisher run (commit-direct mode, 2026-08-11).
--
-- Assets were generated by tools/content-media/generate.mjs from the art-director's
-- media-spec.json, then uploaded to the public `learning-media` bucket and verified
-- (HTTP 200, image/webp) BEFORE this migration ran, so the feed never 404s.
--   cover.webp          768x1152  gemini-api  (textless 2:3: two distant clusters of
--                                              city lights bridged by one lit road —
--                                              the structural hole, rendered literally)
--   infographic.pt.webp 1080x1920 manual      (code-rendered from brand tokens)
--   infographic.en.webp 1080x1920 manual
--
-- NOTE: the first infographic render truncated all three point bodies and the stat
--   caption mid-sentence (4 visible ellipses per locale) because the copy exceeded
--   lib/infographic.mjs's wrap() clamp. Copy was rewritten to the real budgets
--   (point.body <= 118 chars, stat.caption <= 78) and re-rendered to 0 truncations.
--
-- `path` is BUCKET-RELATIVE — the client builds the URL via learningMediaUrl().
-- hero_image_url is the one field that stores a fully-qualified public URL.
-- migrations are write-once; never edit after applying.

update public.learning_material
set hero_image_url = 'https://uneqnpyzevosznwkmvvo.supabase.co/storage/v1/object/public/learning-media/weak-ties-job-search/cover.webp'
where slug = 'weak-ties-job-search';

insert into public.learning_material_media
  (material_id, kind, locale, path, source, meta)
select id, 'infographic', 'pt', 'weak-ties-job-search/infographic.pt.webp', 'manual',
       '{"width": 1080, "height": 1920}'::jsonb
from public.learning_material where slug = 'weak-ties-job-search'
on conflict (material_id, kind, locale) do update set
  path   = excluded.path,
  source = excluded.source,
  meta   = excluded.meta;

insert into public.learning_material_media
  (material_id, kind, locale, path, source, meta)
select id, 'infographic', 'en', 'weak-ties-job-search/infographic.en.webp', 'manual',
       '{"width": 1080, "height": 1920}'::jsonb
from public.learning_material where slug = 'weak-ties-job-search'
on conflict (material_id, kind, locale) do update set
  path   = excluded.path,
  source = excluded.source,
  meta   = excluded.meta;
