-- Ajuste editorial em 3 ideias cujo vídeo do Notebook inventou em cima de frase vaga
-- (runs 2026-10-01/02): circle 4,2x = risco, não 'todos adoeceram'; atomic-habits vontade
-- chega atrasada, não 'se esgota' (ego depletion); career 'mais testados' colava no conselho.
-- Cirúrgico: replace() do trecho exato em ideas->1->body, com guarda.

update learning_material set ideas = jsonb_set(ideas, '{1,body,pt}', to_jsonb(replace(ideas->1->'body'->>'pt', 'ficou resfriado 4,2 vezes mais que quem tinha seis tipos ou mais.', 'teve 4,2 vezes mais chance de ficar resfriado que quem tinha seis tipos ou mais. Nem todo mundo adoeceu nos dois grupos; a diferença está no risco.')))
 where slug = 'glossary-circle' and ideas->1->>'id' = 'variedade-nao-volume' and position('ficou resfriado 4,2 vezes mais que quem tinha seis tipos ou mais.' in ideas->1->'body'->>'pt') > 0;
update learning_material set ideas = jsonb_set(ideas, '{1,body,en}', to_jsonb(replace(ideas->1->'body'->>'en', 'caught a cold 4.2 times more often than those with six types or more.', 'were 4.2 times more likely to catch a cold than those with six types or more. Not everyone got sick in either group; the difference is in the risk.')))
 where slug = 'glossary-circle' and ideas->1->>'id' = 'variedade-nao-volume' and position('caught a cold 4.2 times more often than those with six types or more.' in ideas->1->'body'->>'en') > 0;
do $$ begin if not exists (select 1 from learning_material where slug = 'glossary-circle' and position('teve 4,2 vezes mais chance de ficar resfriado que quem tinha seis tipos ou mais. Nem todo mundo adoeceu nos dois grupos; a diferença está no risco.' in ideas->1->'body'->>'pt') > 0) then raise exception 'edit not applied: glossary-circle pt'; end if; end $$;
do $$ begin if not exists (select 1 from learning_material where slug = 'glossary-circle' and position('were 4.2 times more likely to catch a cold than those with six types or more. Not everyone got sick in either group; the difference is in the risk.' in ideas->1->'body'->>'en') > 0) then raise exception 'edit not applied: glossary-circle en'; end if; end $$;
update learning_material set ideas = jsonb_set(ideas, '{1,body,pt}', to_jsonb(replace(ideas->1->'body'->>'pt', '— quando a vontade entra em cena, a deixa já disparou.', '— não porque a vontade se esgota, mas porque chega atrasada: quando ela entra em cena, a deixa já disparou.')))
 where slug = 'summary-atomic-habits' and ideas->1->>'id' = 'ambiente-vence-vontade' and position('— quando a vontade entra em cena, a deixa já disparou.' in ideas->1->'body'->>'pt') > 0;
update learning_material set ideas = jsonb_set(ideas, '{1,body,en}', to_jsonb(replace(ideas->1->'body'->>'en', '— by the time willpower arrives, the cue has already fired.', '— not because willpower runs out, but because it shows up late: by the time it arrives, the cue has already fired.')))
 where slug = 'summary-atomic-habits' and ideas->1->>'id' = 'ambiente-vence-vontade' and position('— by the time willpower arrives, the cue has already fired.' in ideas->1->'body'->>'en') > 0;
do $$ begin if not exists (select 1 from learning_material where slug = 'summary-atomic-habits' and position('— não porque a vontade se esgota, mas porque chega atrasada: quando ela entra em cena, a deixa já disparou.' in ideas->1->'body'->>'pt') > 0) then raise exception 'edit not applied: summary-atomic-habits pt'; end if; end $$;
do $$ begin if not exists (select 1 from learning_material where slug = 'summary-atomic-habits' and position('— not because willpower runs out, but because it shows up late: by the time it arrives, the cue has already fired.' in ideas->1->'body'->>'en') > 0) then raise exception 'edit not applied: summary-atomic-habits en'; end if; end $$;
update learning_material set ideas = jsonb_set(ideas, '{1,body,pt}', to_jsonb(replace(ideas->1->'body'->>'pt', 'um dos programas mais testados da psicologia', 'uma das teorias mais estudadas da psicologia')))
 where slug = 'glossary-career' and ideas->1->>'id' = 'autonomia-alavanca' and position('um dos programas mais testados da psicologia' in ideas->1->'body'->>'pt') > 0;
update learning_material set ideas = jsonb_set(ideas, '{1,body,pt}', to_jsonb(replace(ideas->1->'body'->>'pt', '**Escolha uma coisa nesta semana que você passa a fazer do seu jeito.**', '**Escolha uma coisa nesta semana que você passa a fazer do seu jeito** — como teste, não como garantia.')))
 where slug = 'glossary-career' and ideas->1->>'id' = 'autonomia-alavanca' and position('**Escolha uma coisa nesta semana que você passa a fazer do seu jeito.**' in ideas->1->'body'->>'pt') > 0;
update learning_material set ideas = jsonb_set(ideas, '{1,body,en}', to_jsonb(replace(ideas->1->'body'->>'en', 'one of the most heavily tested programs in psychology', 'one of the most studied theories in psychology')))
 where slug = 'glossary-career' and ideas->1->>'id' = 'autonomia-alavanca' and position('one of the most heavily tested programs in psychology' in ideas->1->'body'->>'en') > 0;
update learning_material set ideas = jsonb_set(ideas, '{1,body,en}', to_jsonb(replace(ideas->1->'body'->>'en', '**Pick one thing this week that you start doing your own way.**', '**Pick one thing this week that you start doing your own way** — as a test, not a guarantee.')))
 where slug = 'glossary-career' and ideas->1->>'id' = 'autonomia-alavanca' and position('**Pick one thing this week that you start doing your own way.**' in ideas->1->'body'->>'en') > 0;
do $$ begin if not exists (select 1 from learning_material where slug = 'glossary-career' and position('uma das teorias mais estudadas da psicologia' in ideas->1->'body'->>'pt') > 0) then raise exception 'edit not applied: glossary-career pt'; end if; end $$;
do $$ begin if not exists (select 1 from learning_material where slug = 'glossary-career' and position('**Escolha uma coisa nesta semana que você passa a fazer do seu jeito** — como teste, não como garantia.' in ideas->1->'body'->>'pt') > 0) then raise exception 'edit not applied: glossary-career pt'; end if; end $$;
do $$ begin if not exists (select 1 from learning_material where slug = 'glossary-career' and position('one of the most studied theories in psychology' in ideas->1->'body'->>'en') > 0) then raise exception 'edit not applied: glossary-career en'; end if; end $$;
do $$ begin if not exists (select 1 from learning_material where slug = 'glossary-career' and position('**Pick one thing this week that you start doing your own way** — as a test, not a guarantee.' in ideas->1->'body'->>'en') > 0) then raise exception 'edit not applied: glossary-career en'; end if; end $$;
